[package]
name = "rusting-links"
version = "0.1.0"
authors = ["Willow DeKock <willowdekock@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fixedbitset = "0.3.0"